# Generated by Django 5.2.7 on 2025-10-31 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('languages', models.CharField(help_text='Comma-separated', max_length=255)),
                ('bio', models.TextField()),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('On a Trek', 'On a Trek'), ('Busy', 'Busy')], default='Available', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
