# Generated by Django 5.2.7 on 2025-10-31 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Annapurna', 'Annapurna'), ('Everest', 'Everest'), ('Langtang', 'Langtang'), ('Mustang', 'Mustang'), ('Manaslu', 'Manaslu'), ('Dolpo', 'Dolpo'), ('Kanchenjunga', 'Kanchenjunga'), ('Makalu', 'Makalu'), ('Rolwaling', 'Rolwaling'), ('Api-Nampa', 'Api-Nampa')], max_length=50)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('max_altitude', models.IntegerField()),
                ('season_spring', models.BooleanField(default=False)),
                ('season_summer', models.BooleanField(default=False)),
                ('season_autumn', models.BooleanField(default=False)),
                ('season_winter', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult'), ('Extreme', 'Extreme')], max_length=20)),
                ('interest_scenic', models.BooleanField(default=False)),
                ('interest_adventure', models.BooleanField(default=False)),
                ('interest_photography', models.BooleanField(default=False)),
                ('interest_wildlife', models.BooleanField(default=False)),
                ('interest_cultural', models.BooleanField(default=False)),
                ('interest_family', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured_image', models.ImageField(upload_to='treks/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
