# Generated by Django 4.2.7 on 2026-01-25 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_esewa_payment_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
